### PR TITLE
Added solution for the problem: TheatreSquare-1A

### PR DESCRIPTION
**Pull request by abhi27-web**

### CODE REVIEW

**Comment by virejdasani** [comment]
Hi there @abhi27-web, thanks for contributing! Before I can merge, please refer to the contributing guidelines
> For Problem set names with more than one word, don't use spaces. Use WordCapitalization

**Comment by abhi27-web** [comment]
Done, made the changes!

**Comment by virejdasani** [comment]
Looks good, going ahead with the merge. Happy Hacktoberfest!

**Comment by abhi27-web** [comment]
hey, @virejdasani I have already completed the work, you merged the PR. But still on the hacktoberfest dashboard it shows: Matures in 14 days. 

It doesn't come in completed slot. It is still in "IN PROGRESS"

**Comment by abhi27-web** [comment]
> > hey, @virejdasani I have already completed the work, you merged the PR. But still on the hacktoberfest dashboard it shows: Matures in 14 days.
> > It doesn't come in completed slot. It is still in "IN PROGRESS"
> 
> @abhi27-web, the people over at Hacktoberfest have to review your PR once it has been merged. It takes them upto 14 days to review the PR. Once they review it and approve it (which in this case they should), it'll show up as completed

Hey, it has been almost 13 days, it has not been approved. But it is written 1 days left on the page.

**Comment by virejdasani** [comment]
@abhi27-web, be patient, it'll get approved by tomorrow :)

**Comment by abhi27-web** [comment]
> @abhi27-web, be patient, it'll get approved by tomorrow :)

Thank you!!

**Pull request merged**
