### PR TITLE
Code Force Solution - Caps in Kotlin

### PR DESCRIPTION
**Pull request by regan-hoffman**
#### Make sure all the item in the checklist have been done before making the PR

- [x] You have starred the repo
- [x] If you have added a new folder, there are no spaces in the name of the folder
- [x] The link to the problem set is present on the first line of the code file

### CODE REVIEW

**Comment by reganlaurell** [comment]
Ahh did not know you had to do that. Done, should be good now. My apologies. Thanks your help!

**Comment by virejdasani** [comment]
@reganlaurell, this gives a compilation error in Kotlin 1.5

**Comment by reganlaurell** [comment]
Hmm can you provide the error? I am able to have the code run on code forces successfully with Kotlin 1.4 and 1.5
Screen Shot 2021-10-09 at 10 55 38 AM

**Comment by virejdasani** [comment]
Looks good :)

**Pull request merged**
