### PR TITLE
DiameterOfGraph-1581B Problem Added

### PR DESCRIPTION
**Pull request by KIRTIKUMARKK21**
#### Make sure all the item in the checklist have been done before making the PR

- [x ] You have starred the repo
- [x] If you have added a new folder, there are no spaces in the name of the folder
- [x] The link to the problem set is present on the first line of the code file

### CODE REVIEW

**Comment by virejdasani** [comment]
Looks good, Happy Hacktoberfest!

**Comment by virejdasani** [comment]
@all-contributions please add @KIRTIKUMARKK21 for code

**Comment by virejdasani** [comment]
@all-contributors please add @KIRTIKUMARKK21 for code

**Comment by KIRTIKUMARKK21** [comment]
Can I add some more Questions?

**Comment by virejdasani** [comment]
@KIRTIKUMARKK21 of course you can! Go ahead and make a PR!

**Pull request merged**
